# Generated by Django 3.2.4 on 2021-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Completo')),
                ('photo', models.ImageField(blank=True, upload_to='static/PFP/')),
                ('cellphone', models.CharField(max_length=30, verbose_name='telefono')),
                ('direction', models.CharField(max_length=30, verbose_name='dirección')),
                ('mail', models.CharField(max_length=30, verbose_name='email')),
                ('city', models.CharField(max_length=30, verbose_name='pais')),
            ],
        ),
    ]
